<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="CelesteMod.props" />

  <PropertyGroup>
    <CelesteRootPath>C:\Program Files (x86)\Steam\steamapps\common\Celeste</CelesteRootPath>
    <AssemblyName>MiaoNet</AssemblyName>
    <RootNamespace>Celeste.Mod.MiaoNet</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ModAssetsCopyType>link</ModAssetsCopyType>
    <UseCelesteAnalyzer>false</UseCelesteAnalyzer>
    <UseCelestePublicizer>true</UseCelestePublicizer>
    <DefineConstants>$(DefineConstants);MIAO_CLIENT;SAFE_GUARD</DefineConstants>
    <DefineConstants Condition="$(Configuration) == 'Debug'">$(DefineConstants);PACKET_TRACING</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../MiaoNet.Shared/**/*.cs" Exclude="../MiaoNet.Shared/Primitives/**/*.cs" LinkBase="0-Shared" />
    <Compile Include="../ChatInputBox/ChatInputBox/**/*.cs" LinkBase="0-Shared/ChatInputBox" />
		<Compile Include="../MiaoNet.ClientShared/**/*.cs" LinkBase="1-ClientShared" />

		<None Include="CelesteMod*" Visible="false" />
  </ItemGroup>

  <ItemGroup Condition="$(UseLocalhostPfx) == 'true'">
    <EmbeddedResource Include="../localhost.pfx" LogicalName="localhost.pfx" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ClientRC/success.html" LogicalName="ClientRC.success.html" />
  </ItemGroup>
    
  <ItemGroup>
    <CelesteModReference Include="UIHelper" />
  </ItemGroup>

  <Import Project="CelesteMod.targets" />
</Project>