<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="CelesteMod.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <CelesteRootPath>C:/Program Files (x86)/Steam/steamapps/common/Celeste</CelesteRootPath>
    <RootNamespace>Celeste.Mod.ChatInputBoxExample</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseCelesteAnalyzer>false</UseCelesteAnalyzer>
    <UseCelestePublicizer>true</UseCelestePublicizer>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../ChatInputBox/**/*.cs" LinkBase="0-ChatInputBox" />
		<!-- TODO we can move ChatText.Render to ChatInputBox but then we have to make the entire MiaoNetFont into an interface -->
		<Compile Include="../../MiaoNet.Client/Game/ScalelessChatTextRenderer.cs" LinkBase="0-MiaoNet.Font" />
		<Compile Include="../../MiaoNet.Client/Game/MiaoNetFont.cs" LinkBase="0-MiaoNet.Font" />
		
    <None Include="CelesteMod.props">
      <Visible>false</Visible>
    </None>
    <None Include="CelesteMod.targets">
      <Visible>false</Visible>
    </None>
  </ItemGroup>

  <Import Project="CelesteMod.targets" />
</Project>