<Project>

  <PropertyGroup>
    <LangVersion>14</LangVersion>
    <UseLocalhostPfx>false</UseLocalhostPfx>
    <UseLocalhostPfx Condition="$(Configuration) == 'Debug'">true</UseLocalhostPfx>
    <UseCeleMiaoAuth Condition="'$(UseCeleMiaoAuth)' == '' and '$(Configuration)' == 'Release'">true</UseCeleMiaoAuth>
    <UseCeleMiaoAuth Condition="'$(UseCeleMiaoAuth)' == ''">false</UseCeleMiaoAuth>

    <DefineConstants Condition="$(UseLocalhostPfx) == 'true'">$(DefineConstants);USE_LOCALHOST_PFX</DefineConstants>
    <DefineConstants Condition="$(UseCeleMiaoAuth) == 'true'">$(DefineConstants);USE_CELEMIAO_AUTH</DefineConstants>
  </PropertyGroup>

  <PropertyGroup>
    <ProjectRootDirectory>$(MSBuildThisFileDirectory)</ProjectRootDirectory>
    <PathMap Condition="$(Configuration)=='Release'">$(ProjectRootDirectory)=~/</PathMap>
  </PropertyGroup>

  <PropertyGroup>
    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>

  <PropertyGroup>
    <AnalysisModeGlobalization>All</AnalysisModeGlobalization>
  </PropertyGroup>
  
</Project>
